# Generated by Django 5.0.7 on 2024-07-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_contact_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the vendor.', max_length=100, unique=True)),
                ('website', models.URLField(blank=True, help_text='The website of the vendor.')),
                ('agent_name', models.CharField(blank=True, help_text='The name of the agent of the vendor.', max_length=100)),
                ('agent_email', models.EmailField(blank=True, help_text='The email of the agent of the vendor.', max_length=254)),
                ('agent_phone', models.CharField(blank=True, help_text='The phone number of the agent of the vendor.', max_length=20)),
                ('work_phone', models.CharField(blank=True, help_text='The work phone number of the vendor.', max_length=20)),
            ],
        ),
    ]
