# Generated by Django 5.0.7 on 2024-07-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Supplier',
        ),
    ]
