# Generated by Django 5.0.7 on 2024-07-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_vendor_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='google_maps',
            field=models.URLField(blank=True, help_text='The Google Maps link of the vendor.'),
        ),
    ]
