# Generated by Django 5.0.7 on 2024-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_supplier_google_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='The notes of the vendor.'),
        ),
    ]
